apiVersion: v1
kind: Pod
metadata:
  name: chewie
  namespace: yoda
spec:
  containers:
  - name: chewie
    image: busybox:stable
    command: ["sh", "-c", "echo daily message: $(cat /config/planet); while true; do sleep 5; done"]
    volumeMounts:
    - name: kenobi-cm
      mountPath: /etc/starwars

  volumes:
    - name: kenobi-cm
      configMap:
        name: kenobi
